apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-front
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DavoA/kubernetes-manifests.git
    targetRevision: main
    path: front-manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false